baseURL: "https://blog.imych.one/"
title: "YC Photography"
languageCode: "zh-TW"
theme: papermod

permalinks:
  post: "/:filename/"
  categories: "/categories/:slug/"

author:
  name: yc油成
  homepage: https://imych.one
menu:
  main:
    - identifier: about
      name: 關於
      url: /about/
      weight: 99
    - identifier: categories
      name: 分類
      url: /categories/
      weight: 2
    - identifier: tags
      name: 標籤
      url: /tags/
      weight: 3
    - identifier: invitation-code
      name: 邀請碼
      url: /invitation-code/
      weight: 1

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "YC Photography"
  description: "願以照片攝下生活，一場人生中的旅行，從此展開。"
  keywords: [Blog, Technologic, CTF, Program]
  author: 
    name: "油成"
  # author: ["Me", "You"] # multiple authors
  images: ["./images/banner.webp"]
  # DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # Social
  social: 
    facebook_admin: ""

  # ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  # UseHugoToc: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://imych.one/assets/youu.png"
    favicon16x16: "https://imych.one/assets/youu.png"
    favicon32x32: "https://imych.one/assets/youu.png"
    apple_touch_icon: "https://imych.one/assets/youu.png"
    safari_pinned_tab: "https://imych.one/assets/youu.png"

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: ""
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "願以照片攝下生活，一場人生中的旅行，從此展開。"
    imageUrl: "./images/banner.webp"

  

  # socialIcons:
  #   - name: website
  #     url: "https://imych.one"
  #   - name: github
  #     url: "https://github.com/yc97463"
  #   - name: linkedin
  #     url: "https://www.linkedin.com/in/yc97463/"
  #   - name: telegram
  #     url: https://t.me/yc97463
  #   - name: facebook
  #     url: https://www.facebook.com/yc97463
  #   - name: instagram
  #     url: https://www.instagram.com/yc97463/

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
